### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by schef** [jcard0na/haxo-hw#12]
Hi, I'm from the band Scifidelity Orchestra. I would like to integrate the instrument into the show. Would you sacrifice one for the promotion? :)

**Comment by jcard0na** [comment]
Hi schef,

I don't really have any spare haxophones...  Your current options to get one are:
1. Wait for the crowd supply campaign and order one there: https://www.crowdsupply.com/cardona-bits/haxophone
2. Join [this discussion](https://github.com/jcard0na/haxo-hw/discussions/10) with the people who want to pool together to order their own batch of PCBs and build their own.

Best,
Javier

**Comment by schef** [comment]
Thanks for the fast anwser!
