### ISSUE TITLE
Raspberry Pi alternative solutions

### ISSUE THREAD

**Issue by Woovie** [jcard0na/haxo-hw#19]
Hello!

I really want to build one of these, but it's damn near impossible to find in stock Raspberry Pi's from my searching. Would the RP2040 suffice? If so, I'd love to have a design that supports this instead purely for the sake of actually obtaining one in a timeframe sub 1 year.

I've done some relatively minor PCB designs in my time and could probably hack the idea together, but I'm unfamiliar with the viability here.

Thanks

**Comment by jcard0na** [comment]
Hi @Woovie ,

The RP2040 cannot replace a Raspberri Pi in the haxophone, at least in the current design where we synthesize sounds with fluidsynth.
That said, you are not limited to just the Pi Zero:  you can also use the Pi Zero W, the RPi3 or the RPi4.  The last two are a bit of extra weight and more expensive, but give you a good development environment, in case you want to extend/modify the software on the haxophone.  
Cheers,

By the way, this is a good site to look for Raspberry Pi inventory: https://rpilocator.com/

**Comment by Woovie** [comment]
I appreciate it. Good point on fluidsynth, I didn't look at that close enough. I'll hunt down a Pi then, thank you!
