### ISSUE TITLE
Corrupt 3d files

### ISSUE THREAD

**Issue by mikenturner** [jcard0na/haxo-hw#21]
Hi
I've tried a number of 3d printing services and they are reporting that the .stl files are either corrupt or that processing fails.  I tried the .step files as well,
<img width="909" alt="2023-05-31 (1)" src="https://github.com/jcard0na/haxo-hw/assets/60625283/657971f0-0b4a-48bc-97c2-a0817b99f444">
<img width="941" alt="2023-05-31 (2)" src="https://github.com/jcard0na/haxo-hw/assets/60625283/094d4211-a10f-4e6d-9cf8-e73167e1b198">
 and if they get processed they report that the volume is too low for printing,.  See a couple of screenshots as examples.
Mike

**Comment by jcard0na** [comment]
Hi Mike,

For 3D printing you need to use the `.stl` file, not `.step`.
I just tested Sculpteo and impressao3dportugal.com and the files are loaded correctly.  

![Screenshot 2023-05-31 at 16 43 47](https://github.com/jcard0na/haxo-hw/assets/676181/4b61cb6b-74ba-4344-bd0e-a0e38b3eed4b)
![Screenshot 2023-05-31 at 16 51 58](https://github.com/jcard0na/haxo-hw/assets/676181/ba7d758e-b67f-48b4-ae2a-500adb021f28)
![Screenshot 2023-05-31 at 16 53 18](https://github.com/jcard0na/haxo-hw/assets/676181/af8bd904-5715-49cf-89a4-208187f77647)

```
md5 *.stl   
MD5 (hook_rest-Part.stl) = 22d6e1990d6d020719939e806fbd390a
MD5 (neck-neck.stl) = 9ed0153b7fa52ee1ccf8f4bf9de990f8
MD5 (octave_rest-Part.stl) = 5782e400a41bb528da39ed18cb579046
```

**Comment by jcard0na** [comment]
Excellent!   Thanks for confirming that it worked.
