### ISSUE TITLE
Share BOM, CPL, gerber files for easier JLCPCB ordering

### ISSUE THREAD

**Issue by cedricium** [jcard0na/haxo-hw#9]
Hiya! Came across this project after seeing it on Hacker News and immediately wanted to order everything to make one myself. Unfortunately I don't have access to KiCad and therefore am unable to follow what seems like the most crucial step of getting started: ordering all the parts and PCB.

Would love if the output of the `ordering_process.md` guide (zipped gerbers, CPL, and BOM files) could be shared as part of this repository so ordering was easier. (Or better yet, maybe start a Tindie store to order the PCBs.)

For inspiration, The Open Book shares these files: https://github.com/joeycastillo/The-Open-Book/tree/main/eBook%20Feather%20Wing

**Comment by jcard0na** [comment]
Good suggestion and thanks for the link.
I'll share the fabrication files this week.  As for Tinder, I need to read up on that.  I'm not looking to manage inventory, returns, etc. so I'd only take that route if they handle that.

**Comment by cedricium** [comment]
The fab files would be more than enough, thank you kindly. Can't wait to get build one of my own!

**Comment by jcard0na** [comment]
I have checked in the fabrication files [here](https://github.com/jcard0na/haxo-hw/tree/main/builds)
The good news is that when I dry-run an order with JLPCB, all the components seem to be in stock.  You can order 5 boards for ~200 USD, or $40 per board.  Of that price, a full $22 go to the pressure sensor, a part that was $8 when I started the project!.

![image](https://user-images.githubusercontent.com/676181/205176711-0397ad4c-9aad-4ea8-96ba-e1028bc15f94.png)

This version of the board is different from the one I built, as I had to swap the parts that were difficult to source.  Also, I moved to the latest version of Kicad, which also required a few tweaks to the design.  In other words, **THESE ARE NOT THE EXACT SAME FABRICATION FILES I USED AND THERE IS A NON NEGLIGIBLE CHANCE THAT THE BOARD DOES NOT WORK FOR YOU**.  Please only order if you enjoy challenging projects that you can make your own.

I'll close this issue now.  If you end up ordering, feel free to open a new issue so I can support you with board bring up.  You could also open an issue to try and pool 5 or more people together to place an order with JLCPCB as 5 is the minimum quantity.

Cheers!
